death:
  togglePlugin: true
  toggleDeathMessage: true # Does the message sent after death
  deathMessageType: 1 # 0 - Chat, 1 - Action Bar, 2 - Title, 3 - Subtitle
  deathMessage: "You died, so you were transferred to Spectator Mode"
  deathMessageColor: "#FFC300" # Message's color in HEX

ban:
  toggleBan: true # Does the player get banned after death
  banTime: 8 # Time before ban in seconds
  banMessage: "You'll be banned in {time} seconds" # Message sent to player
  banMessageType: 1 # 0 - Chat, 1 - Action Bar, 2 - Title, 3 - Subtitle
  banMessageColor: "#FF5733" # Message's color in HEX
  banReason: "You're lost!" # Reason of ban
  banReasonColor: "GOLD" # Reason's color (used org.bukkit.ChatColor)

plugin:
  removePlayerFromBanlistOnRestart: true # Remove players from banlist if they aren't banned?

messages:
  noPermission: "You dont have enough permissions!"
  noPermColor: "#ff3630"

  configReload: "Config reloaded!"
  configReloadColor: "#30ff36"

  unbannedPlayer: "Pardoned {playerName}!"
  unbannedPlayerColor: "#30ff36"

  playerIsntBanned: "{playerName} isn't banned!"
  playerIsntBannedColor: "#ff3630"

  listIsEmpty: "Banlist is empty!"
  listIsEmptyColor: "#ff3630"


bannedPlayers:
  - "Notch"